Support reading YAML files with classic Java objects
cognitedata/cdf-beam-connector-java pull request #33
Opened 2021-07-26 07:48 UTC by pavelzubarev

2021-07-26 08:00 UTC, pavelzubarev commented
Side question: What is our current practice for consuming such SNAPSHOT packages (except the local build)? Should we publish snapshots as well?

2021-07-26 09:48 UTC, pavelzubarev commented
More I look on it, more I think it should be part of my pipeline and not SDK at this stage, actually

2021-07-27 17:16 UTC, kjetilh33 requested changes

2021-07-27 17:16 UTC, kjetilh33 commented on src/main/java/com/cognite/beam/io/transform/yaml/ReadYamlObjectMap.java
> +    abstract Class<T> getKlass();
Are we able to find a better name? "getTargetClass()", "getOutputClass()" or similar?

2021-07-27 17:18 UTC, kjetilh33 commented
> Side question: What is our current practice for consuming such SNAPSHOT packages (except the local build)? Should we publish snapshots as well?

Per now we haven't published the SNAPSHOT packages. I don't have any specific preferences to be honest.

2022-01-18 16:38 UTC, closed without merging